### ISSUE TITLE
Main actor isolation errors in LinkText and TextFieldClearButton

### ISSUE THREAD

**Issue by gmckenzi** [danielsaidi/SwiftUIKit#31]
I just pulled this package into a new project with Xcode 16.2, building for iOS, and when building there are main-actor isolation errors in LinkText and TextFieldClearButton.

**Comment by danielsaidi** [comment]
Hi @gmckenzi 

Thank you for notifying me! Things must have changed in how Xcode handles concurrency since I released the 5.0, since the code worked then.

I have released a patch that fixes this, with the unfortunate side-effect that `LinkText` has breaking changed. You can try it out in the `5.0.1` version.

https://github.com/danielsaidi/SwiftUIKit/releases/tag/5.0.1
