### ISSUE TITLE
Documenation Zip File is missing

### ISSUE THREAD

**Issue by matthiaszarzecki** [danielsaidi/SwiftUIKit#7]
Hello,
I just wanted to download the documentation, but it turns out the link `https://github.com/danielsaidi/SwiftUIKit/raw/master/Docs/SwiftUIKit.doccarchive.zip` in the readme is returning a 404, and the file does not seem to exist within th repository.

Would love to be able to download and read it! :)

Best, Matthias

**Comment by danielsaidi** [comment]
Hi @matthiaszarzecki 

Oh, I must have forgotten to update it. Thanks for notifying me!

Since the documentation files become large for some projects, I don't want to bloat the repo with these huge files. I tried using git LFS (https://git-lfs.github.com) which worked great, but unfortunately Xcode couldn't handle packages from repos that used it, so I had to backtrack.

I will therefore setup a separate repo, where I'll place all pre-build documentation files. Until then, you can just download SwiftUIKit and either build the documentation with Fastlane or open it in Xcode and build the documentation from there.

I'll keep this issue around until I've fixed this.

**Comment by danielsaidi** [comment]
@matthiaszarzecki - the documentation is available once more 👍

**Comment by matthiaszarzecki** [comment]
Sweet, thanks for updating! :)
