### ISSUE TITLE
GIF/Images of the Demo

### ISSUE THREAD

**Issue by saamerm** [danielsaidi/SwiftUIKit#8]
Hi Daniel! I just saw this from your Twitter and it looks pretty awesome and resourceful.
It would be amazing to see a GIF of the demo, or just images so people can instantly see if the kit has stuff that would be useful for them, without having to clone the repo!

**Comment by danielsaidi** [comment]
Hi @saamerm 👋 

Yeah, I totally agree! However, I'm not really sure what that short gif should demonstrate, since the library contains so many things. I guess a YouTube video would be better.

I am however at a state where I consider moving things out of the library into their own micro libraries instead, such as the presentation stuff, list items, web view, page view etc. I think that will make it easier for people to find exactly what they're after and for me to show what the library is all about.
